name: Deploy to Azure Functions

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      
      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'
          
      - name: Install dependencies
        run: npm install
        
      - name: Remove dev dependencies and install production only
        run: |
          rm -rf node_modules/
          npm install --production
          
      - name: Deploy to Azure Functions
        uses: Azure/functions-action@v1
        with:
          app-name: 'consigmais'
          package: '.'
          publish-profile: ${{ secrets.AZURE_FUNCTIONAPP_PUBLISH_PROFILE }}
