name: Deploy Azure Function

on:
  push:
    branches: [ main ]  # para prod
    branches: [ develop ]  # para dev

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v3
    
    - name: Setup Node.js
      uses: actions/setup-node@v3
      with:
        node-version: '18'
        
    - name: Install dependencies
      run: npm install
        
    - name: Deploy to Azure Functions
      uses: Azure/functions-action@v1
      with:
        app-name: 'your-function-app-name'
        package: '.'
        publish-profile: ${{ secrets.AZURE_FUNCTIONAPP_PUBLISH_PROFILE }}
