name: Deploy Azure Function App

on:
  push:
    branches: 
      - main
  workflow_dispatch:

env:
  AZURE_FUNCTIONAPP_NAME: 'consigmais'   # Nome correto da sua Function App
  NODE_VERSION: '18.x'
  AZURE_FUNCTIONAPP_PACKAGE_PATH: '.'

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v3

    - name: Setup Node.js
      uses: actions/setup-node@v3
      with:
        node-version: ${{ env.NODE_VERSION }}
        
    - name: Install dependencies
      run: |
        npm install
        npm run build --if-present
        
    - name: 'Deploy Azure Function'
      uses: Azure/functions-action@v1
      id: deploy
      with:
        app-name: ${{ env.AZURE_FUNCTIONAPP_NAME }}
        package: ${{ env.AZURE_FUNCTIONAPP_PACKAGE_PATH }}
        publish-profile: ${{ secrets.AZURE_FUNCTIONAPP_PUBLISH_PROFILE }}
        scm-do-build-during-deployment: true
